### PR TITLE
Explicit type annotation for unit

### PR DESCRIPTION
**Pull request by a-c-sreedhar-reddy**
fixes - #383

### CODE REVIEW

**Review by IwanKaramazow — COMMENTED** [review]
Hey @a-c-sreedhar-reddy, thanks for picking this up =D 

I wonder if we can solve this in a more general way. What if someone aliases `type u = unit` and then writes `let foo = ((): u)`? 

Maybe we can just see if the token after the `:` is an `Lident`, consume the token and then check if there's a `=>` ?

**Comment by a-c-sreedhar-reddy** [comment]
Hi @IwanKaramazow . I have added the changes.  

If it is after 
 Colon, Lident _ if the next token is EqualGreater we return true else false.

**Comment by a-c-sreedhar-reddy** [comment]
This would fail for this case 
```
type d<'a,'b>
let c = ():d<'a,'b> => 9
```
How can I parse the entire type expression after Colon and then search for => instead of using Lident?

**Comment by a-c-sreedhar-reddy** [comment]
Hi @IwanKaramazow 
I have updated the PR.
instead of checking for `=>` immediately after `Lident`, we would skip `<int,int>` parts and then look for `=>`.

**Comment by IwanKaramazow** [comment]
Thanks for the work @a-c-sreedhar-reddy, we're getting there. Next step would be to add some tests in `tests/parsing/grammar/expressions/arrow.res`.

We can also add the test case from https://github.com/rescript-lang/syntax/issues/359, which suffers from the same problem.

Could you also add a comment above every branch where you match on a token with an example?
Example:
```
match token with
(* arrived at `()` here *)
| Rparen
```

> How can I skip the entire type expression after the Colon and then search for => instead of using Lident?

The detection of arrow functions works based on heuristics, we could do a full parse. But I don't know if it's worth the additional complexity. Handling the most common cases seems like a good first step. How do you feel about this?

**Comment by a-c-sreedhar-reddy** [comment]
> Next step would be to add some tests in `tests/parsing/grammar/expressions/arrow.res`

Hi @IwanKaramazow I have added the tests and also the comments.

**Comment by IwanKaramazow** [comment]
Awesome thanks! Trying to think of additional edge cases, but I think this looks ready.

**Comment by IwanKaramazow** [comment]
@a-c-sreedhar-reddy  Thanks for your work! Really appreciate the effort. Let's merge.

**Comment by a-c-sreedhar-reddy** [comment]
Thanks @IwanKaramazow

**Pull request merged**
