### PR TITLE
Remove key prop from JSX props type

### PR DESCRIPTION
**Pull request by mattdamon108**
* Remove the key prop from the props type
* Add magic ~~`React.addKeyProp`~~`Jsx.addKeyProp` for the type checking

### CODE REVIEW

**Comment by mattdamon108** [comment]
I noticed that `type domProps` has the `key: string` too. It is used for the lowercase such as `<div key="k" />`. Is it also needed to be removed? https://github.com/rescript-lang/rescript-react/blob/46944b490ee1923cfb69fa5ef0bd3095f93d18de/src/ReactDOM.res#L58

**Comment by mattdamon108** [comment]
Does the lowercase have the same context? https://github.com/rescript-lang/rescript-compiler/issues/5646#issuecomment-1243607315

**Comment by mattdamon108** [comment]
I think the lowercase wouldn't be a problem, because it is still use the `@deriving(abstract)`.

```rescript
ReactDOMRe.createDOMElementVariadic("div", ~props=ReactDOMRe.domProps(~key="k", ()), []),
```

**Comment by cristianoc** [comment]
I think lowercase is OK

**Comment by cristianoc** [comment]
Would you update the spec too?

**Comment by mattdamon108** [comment]
> Would you update the spec too?

https://github.com/rescript-lang/syntax/pull/635/commits/0fbf9a7abe521f6d34bcd41fd8d6ef5b7aa93b2f

**Review by cristianoc — APPROVED** [review]
This is great.
Anything missing?

**Comment by mattdamon108** [comment]
> This is great. Anything missing?

Thanks.
No, it seems done.

**Pull request merged**
