### PR TITLE
WIP: Run CI build for macOS, Linux and Windows

### PR DESCRIPTION
**Pull request by cknitt**

### CODE REVIEW

**Comment by IwanKaramazow** [comment]
@cknitt thanks for the initiative, but running the tests on an additional platform(s) won’t test anything meaningful. The compiler’s integration tests should cover it.

**Comment by cknitt** [comment]
Ok, no problem.

This means that if/when we merge the syntax repo into the rescript-compiler repo, the parser tests will only be run for macOS, too, whereas we aim to run the other tests in the rescript-compiler repo for all three platforms?

**Comment by cknitt** [comment]
@IwanKaramazow One benefit of building for multiple platforms would also be that we could automatically provide the built `rescript.exe` as an artifact for each platform on each commit.

**Comment by cknitt** [comment]
Done with #505.

**Pull request closed without merging**
