### PR TITLE
Fix several printing issues with `async` including an infinite loop.

### PR DESCRIPTION
**Pull request by cristianoc**
See https://github.com/rescript-lang/syntax/issues/679

### CODE REVIEW

**Comment by mattdamon108** [comment]
The pattern matching seems complicated and presumably the Pexp_fun with labeled arg can have attributes, not with Nolabel arg. Is it syntax that only Pexp-fun with Labeled and Optional arg can have attributes?

**Comment by cristianoc** [comment]
> 

Just trying to respect what seem to be the existing conventions. And yes it looks complicated. The attributes I think can be used in JSX to specify `@as` for arguments right?

**Comment by mattdamon108** [comment]
> Just trying to respect what seem to be the existing conventions. And yes it looks complicated. The attributes I think can be used in JSX to specify `@as` for arguments right?

In user space? Not that I know. The attribute for arg is mainly used in `Pstr_primitives`, I mean the external. We use the attributes such as `@as` often when we bind to components or functions. The attribute for `Pexp_fun` is not used as long as I know.
But I see that the output of JSX V3 has `@warning` attributes for arg.

**Comment by mattdamon108** [comment]
In order to make the pattern matching more simple, then I look through several cases of attributes with fun args. I found something strange between labeled and nolabel arg.

```rescript
let f7 = (@attr ~a, @attr ~b) => ()
let f8 = (@attr a, @attr b) => ()
```
```
// (f7) @attr ~a
// @attr is parsed to pexp_attributes
        expression (tests/printer/expr/fun2.res[9,244+9]..[9,244+35])
          attribute "attr" (tests/printer/expr/fun2.res[9,244+10]..[9,244+15])
            []
          Pexp_fun
          Labelled "a"
          None
          pattern (tests/printer/expr/fun2.res[9,244+10]..[9,244+18])
            attribute "ns.namedArgLoc" (tests/printer/expr/fun2.res[9,244+17]..[9,244+18])
              []
            Ppat_var "a" (tests/printer/expr/fun2.res[9,244+10]..[9,244+18])

// (f8) @attr a
// @attr is pared to ppat_attributes
        expression (tests/printer/expr/fun2.res[10,280+9]..[10,280+33])
          Pexp_fun
          Nolabel
          None
          pattern (tests/printer/expr/fun2.res[10,280+16]..[10,280+17])
            attribute "attr" (tests/printer/expr/fun2.res[10,280+10]..[10,280+15])
              []
            Ppat_var "a" (tests/printer/expr/fun2.res[10,280+16]..[10,280+17])
```
Can we parse the attributes for arg to the `ppat_attributes` of arg for both cases? The only `bs` and `res.async` attributes are parsed to `pexp_attributes` in `Pexp_fun`. Then, we may be able to make the more simple implementation of the printer.

**Comment by cristianoc** [comment]
The one thing I'm really not sure about is why labelled and unlabelled args are treated differently.
Wondering whether there's something that might make use of the difference.

Also, this
```res
let f12 = @a (@b x) => 3
```
formats to
```
let f12 = @a x => 3
```

**Comment by mattdamon108** [comment]
I think we need to check this decision history.
https://github.com/rescript-lang/syntax/blob/master/src/res_core.ml#L1537:L1542

**Comment by cristianoc** [comment]
> In order to make the pattern matching more simple, then I look through several cases of attributes with fun args. I found something strange between labeled and nolabel arg.
> 
> ```rescript
> let f7 = (@attr ~a, @attr ~b) => ()
> let f8 = (@attr a, @attr b) => ()
> ```
> 
>  ```
> // (f7) @attr ~a
> // @attr is parsed to pexp_attributes
>         expression (tests/printer/expr/fun2.res[9,244+9]..[9,244+35])
>           attribute "attr" (tests/printer/expr/fun2.res[9,244+10]..[9,244+15])
>             []
>           Pexp_fun
>           Labelled "a"
>           None
>           pattern (tests/printer/expr/fun2.res[9,244+10]..[9,244+18])
>             attribute "ns.namedArgLoc" (tests/printer/expr/fun2.res[9,244+17]..[9,244+18])
>               []
>             Ppat_var "a" (tests/printer/expr/fun2.res[9,244+10]..[9,244+18])
> 
> // (f8) @attr a
> // @attr is pared to ppat_attributes
>         expression (tests/printer/expr/fun2.res[10,280+9]..[10,280+33])
>           Pexp_fun
>           Nolabel
>           None
>           pattern (tests/printer/expr/fun2.res[10,280+16]..[10,280+17])
>             attribute "attr" (tests/printer/expr/fun2.res[10,280+10]..[10,280+15])
>               []
>             Ppat_var "a" (tests/printer/expr/fun2.res[10,280+16]..[10,280+17])
> ```
> 
> Can we parse the attributes for arg to the `ppat_attributes` of arg for both cases? The only `bs` and `res.async` attributes are parsed to `pexp_attributes` in `Pexp_fun`. Then, we may be able to make the more simple implementation of the printer.

Yes this makes sense, and should respect the intent of the original code. Basically attributes outside `( )` would be added to the function, and inside `(...)` to the pattern.
And `async` goes to the function, and uncurried `(. ...)` also go to the function.

Is this ^ what you have in mind?

**Comment by mattdamon108** [comment]
> Yes this makes sense, and should respect the intent of the original code. Basically attributes outside `( )` would be added to the function, and inside `(...)` to the pattern. And `async` goes to the function, and uncurried `(. ...)` also go to the function.
> 
> Is this ^ what you have in mind?

Exactly!
But I'm a little worrying about the reason for the decision to treat differently between labeled arg and nolabed arg. Any side-effect after changing it

**Comment by cristianoc** [comment]
I suspect the distinction was not really intentional, and things just developed this way.
@IwanKaramazow do you remember?

**Comment by IwanKaramazow** [comment]
The distinction was indeed not really intentional, I guess no ReScript developer ever hit this path.

> Basically attributes outside ( ) would be added to the function, and inside (...) to the pattern.
And async goes to the function, and uncurried (. ...) also go to the function.

Exactly! This is also my mental model.

**Comment by cristianoc** [comment]
Proposal, I'll add a few more examples and merge this PR. Will go into 10.1 as it needs to fix async.

Then create an issue about the proper solution discussed here, to go into v11, so there's enough time to figure out if it affects anything.

**Comment by cristianoc** [comment]
https://github.com/rescript-lang/rescript-compiler/issues/5735

**Pull request merged**
