### PR TITLE
Tweak printing of callbacks to break correctly in case of annotated labeled arguments

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Fixes https://github.com/rescript-lang/syntax/issues/190

```rescript
// before
let make = fn((~a: option<string>=?, ~b: option<string>=?, ~c: option<string>=?, ~d: option<
  string,
>=?, ~e: option<string>=?, x) => {
  ()
})

// after
let make = fn((
  ~a: option<string>=?,
  ~b: option<string>=?,
  ~c: option<string>=?,
  ~d: option<string>=?,
  ~e: option<string>=?,
  x,
) => {
  Js.log()
})
```

### CODE REVIEW

**Comment by IwanKaramazow** [comment]
@alexfedoseev what do you think of this layout to fix your issue?

**Comment by IwanKaramazow** [comment]
I wonder if it would be better to have:
```rescript
let make = fn(
  (
    ~a: option<string>=?,
    ~b: option<string>=?,
    ~c: option<string>=?,
    ~d: option<string>=?,
    ~e: option<string>=?,
    x,
  ) => {
    Js.log()
  }
)
```

**Comment by jfrolich** [comment]
Would be better IMO!

**Comment by IwanKaramazow** [comment]
@jfrolich which one of the two are you referring to?

```rescript
// option 1
let make = fn((
  ~a: option<string>=?,
  ~b: option<string>=?,
  ~c: option<string>=?,
  ~d: option<string>=?,
  ~e: option<string>=?,
  x,
) => {
  Js.log()
})

// option 2
let make = fn(
  (
    ~a: option<string>=?,
    ~b: option<string>=?,
    ~c: option<string>=?,
    ~d: option<string>=?,
    ~e: option<string>=?,
    x,
  ) => {
    Js.log()
  }
)
```

**Comment by jfrolich** [comment]
Option 2, makes it more clear that it's a function that receives a callback.

**Comment by alexfedoseev** [comment]
Pro of 1: it doesn’t add +1 stop to a body.
Pro of 2: it’s clearer that argument is a function.

Personally, I’m fine with either. Most likely additional stop won’t be an issue in majority of cases (ppx’es are implemented in reason/ocaml anyway 😃)

**Comment by IwanKaramazow** [comment]
Investigated and option 1 appears to be non-trivial. I'll merge to get the bug fixed and revisit this problem at a later date. Need to get infix operators done. Tracked further in: https://github.com/rescript-lang/syntax/issues/201

**Pull request merged**
