### PR TITLE
Print attributes without the @bs prefix

### PR DESCRIPTION
**Pull request by IwanKaramazow**
*before*
```rescript
@bs.val
@bs.module
```

*after*
```rescript
@val
@module
```

Exceptions:
- @bs.open
- @bs.pipe.send

### CODE REVIEW

**Comment by pckilgore** [comment]
This is generally very cool and good but could it be all-or nothing across annotations? Having a consistently inferior syntax is better than an inconsistent-occasionally nicer syntax (which is already a massive issue with existing *.re code that must share a codebase with any .res for the foreseeable future).

**Comment by IwanKaramazow** [comment]
@pckilgore can you explain yourself more? I included all annotations, except for `@bs.open` and `@bs.send.pipe` because of the latter being deprecated and only there for backwards compatibility.

**Comment by pckilgore** [comment]
Even a deprecated construct might be supported for years.  Unless there's a technical reason to not convert to `@send.pipe`, `@bs.send.pipe` is going to **look** like invalid syntax, or cause folks to think that something might be wrong with the parser because it *usually* rewrites those things. And to the extent discouraging usage of send.pipe is a goal, I would suggest the compiler would be a nice and explicit place to handle that, as it can provide context and explanation vs. inconsistent inferred behavior.  

`@bs.open` doesn't matter much to me if it's invalid syntax entirely (that is, `@open` is invalid).  I suppose I'm a bit curious why it was called out in that case?

**Comment by ryyppy** [comment]
@pckilgore we will document the bs.send.pipe and bs.open as deprecated attributes in our syntax widget, so ppl will still have a chance to understand what those are for, or why they are printed differently.

The compiler will also most likely print a depreciation warning at some point? \cc @bobzhang

**Comment by pckilgore** [comment]
I suppose I'm still curious why not treat them consistently and obviate any possible confusion (and also avoid the need to clutter the documentation with information that will be irrelevant to most).

**Comment by IwanKaramazow** [comment]
It's ok here and won't cause a lot of confusion. The documentation will contain both versions any way.
The printed code will look a bit less cryptic in the same sense that when a user writes `let (x) = ((1) +(2))`, the formatter outputs `let x = 1 + 2`.

Regarding the `@bs.open`, there's still an open issue that needs to be tackled first https://github.com/rescript-lang/syntax/issues/185

**Pull request merged**
