### PR TITLE
Unify JSX docs in a single file.

### PR DESCRIPTION
**Pull request by cristianoc**

### CODE REVIEW

**Comment by cristianoc** [comment]
@mattdamon108 would you review the updated, unified docs?

**Comment by mattdamon108** [comment]
Maybe it is too much though, how about adding some kind of troubleshooting or migration how-to section. e.g. the handwritten component as per v3 before.

**Comment by cristianoc** [comment]
> Maybe it is too much though, how about adding some kind of troubleshooting or migration how-to section. e.g. the handwritten component as per v3 before?

Would you list situations not currently covered but which should be covered, each with an example?

**Comment by mattdamon108** [comment]
> > Maybe it is too much though, how about adding some kind of troubleshooting or migration how-to section. e.g. the handwritten component as per v3 before?
> 
> Would you list situations not currently covered but which should be covered, each with an example?

Sure, during test with community, there are some expected cases. I’ll list up soon.

**Pull request merged**
