### PR TITLE
resdoc: add support for .ml and .res files

### PR DESCRIPTION
**Pull request by Minnozz**
Building on the [experimental-docgen](https://github.com/rescript-lang/syntax/tree/experimental-docgen) branch.

Fixes rescript-association/rescript-lang.org#359

### CODE REVIEW

**Comment by Minnozz** [comment]
A problem with the current `Ast_iterator` approach for structure files is that it recurses into functions, while we only want to document top level stuff.

I've been looking at a way to convert a `structure` into a `signature`, but I can't find it in the codebase. However, the new `dump` subcommand does something similar. Maybe we can use that?

**Comment by IwanKaramazow** [comment]
* Regarding `Ast_iterator`, maybe it's ok to just write your own recursive functions that walk the tree? This way you have full control.

* Converting a `structure` into a `signature` is not possible without access to the type checker.

**Comment by Minnozz** [comment]
@IwanKaramazow Thanks for the tips!

I initially thought using `Ast_iterator` would be better, but I think I'll revert to @ryyppy's approach.

**Comment by IwanKaramazow** [comment]
(Random thought: Control flow is one of the only tools we have as programmers, sometimes it's not worth to give it up.)

**Pull request closed without merging**
