### PR TITLE
Add loc for returned component body

### PR DESCRIPTION
**Pull request by mattdamon108**
This PR fixes the issue https://github.com/rescript-lang/rescript-compiler/issues/5635
It show the error with loc now.

image

### CODE REVIEW

**Comment by cristianoc** [comment]
@mattdamon108  thanks for spotting the location of the issue.

Now for the error message, looking at the error after PPX.

Desugared:
```res
module Foo = {
  let compare = (nextProps, currentProps) => nextProps["foo"] == currentProps["foo"]
  let memo = React.memoCustomCompareProps(_, compare)
  type props<'foo> = {key?: string, foo: 'foo}

  let make = ({foo, _}: props<string>) => React.string(foo)
  let make = memo({
    let \"Tst$Foo" = (props: props<_>) => make(props)

    \"Tst$Foo"
  })
}
```

Error:
```

  We've found a bug for you!
  /Users/cristianocalcagno/GitHub/rescript-vscode/analysis/tests/src/Tst.res:10:5-14

   8 │     let \"Tst$Foo" = (props: props<_>) => make(props)
   9 │ 
  10 │     \"Tst$Foo".    <-------
  11 │   })
  12 │ }

  This has type: props<string> => React.element
  Somewhere wanted:
    React.component<({.."foo": 'b} as 'a)> (defined as 'a => React.element)
  
  The incompatible parts:
    props<string> vs 'a
```

**Comment by cristianoc** [comment]
Alternative JSX behaviour (don't let-define `Tst$Foo`):
```res
module Foo = {
  let compare = (nextProps, currentProps) => nextProps["foo"] == currentProps["foo"]
  let memo = React.memoCustomCompareProps(_, compare)
  type props<'foo> = {key?: string, foo: 'foo}

  let make = ({foo, _}: props<string>) => React.string(foo)
  let make = memo({
    (props: props<_>) => make(props)
  })
}
```

Error:
Screenshot 2022-09-14 at 09 34 30

```

```

**Comment by cristianoc** [comment]
The second one is clearer, but I'm not sure how clearly it can be expressed w.r.t. the original code.

**Comment by cristianoc** [comment]
@mattdamon108  I'm thinking of merging the PR as it is now.
Thoughts?

**Comment by mattdamon108** [comment]
> Alternative JSX behaviour (don't let-define `Tst$Foo`):

Can you show me the js output? The lef-define such as `Tst$Foo` is a secret recipe to make the js output function name starting with the capital letter.

**Review by cristianoc — APPROVED** [review]
Thanks for the fix!
Some discussion in the conversation part of the PR.
If anything, we can tackle that later on.

**Comment by mattdamon108** [comment]
Sorry for missing to add tests 😓 I won't forget next time.

**Comment by cristianoc** [comment]
> > Alternative JSX behaviour (don't let-define `Tst$Foo`):
> 
> Can you show me the js output? The lef-define such as `Tst$Foo` is a secret recipe to make the js output function name starting with the capital letter.

That magic does not apply when the top-level of the body is an application: it simply gets lost.

**Pull request merged**
